config/routes.rb
ZombieRecipes::Application.routes.draw do

  resources :recipes do
    put :vote, on: :member
  end

  resources :zombies
  resources :sessions

  get 'login' => 'zombies#login', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'

  root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :zombie

  default_scope :order => "created_at DESC"
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  has_many :recipes
  before_save :encriptar_pass

  validates_presence_of :password
  validates_confirmation_of :password
  validates_presence_of :mail
  validates_uniqueness_of :mail


  def self.authenticate(email,password)
    # self.findByEmail(email)
    logger.debug "Estem al auth"
    zombie = Zombie.find_by_mail(email)
    salt = "$2a$10$c4NMmE26y3iH7Z7QPe3g3."
    if zombie && zombie.password == BCrypt::Engine.hash_secret(password,salt) then
      zombie
    else
      nil
    end
  end

  def encriptar_pass
    if password.present? 
      salt = "$2a$10$c4NMmE26y3iH7Z7QPe3g3."
      self.password = BCrypt::Engine.hash_secret(password,salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private 
  def current_user
    @current_user ||= Zombie.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::NumberHelper
  
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    @zombies = Zombie.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @zombies = Zombie.all
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.numVotes = 0
    @recipe.rating = 0
    
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1/vote.json
  def vote
    @recipe = Recipe.find(params[:id])
    
    @recipe.rating = ((@recipe.rating * @recipe.numVotes) + params[:valVot].to_i) / (@recipe.numVotes + 1)
    @recipe.numVotes += 1
  
    @recipe.save

    # render json: @recipe.to_json(only: [pluralize(:numVote, 'vot') as :numVote, :rating])
    render json: '{"numVotes":"'+ pluralize(@recipe.numVotes, "vot") + '", "rating":' + number_with_precision(@recipe.rating, precision:0) + '}'
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
     @var = "Byeeeeeeeee"
  end

  def create
     zombie = Zombie.authenticate(params[:mail],params[:password])
     if (zombie) then
        session[:user_id] = zombie.id 
        @login = true
        redirect_to root_path
     else
        @login = false
     end
  end 
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController

  def login
    if (params[:email]) then
      logger.debug(params[:email])
    else 
      logger.debug("post buit")
    end
  end

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZombieRecipes</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
	<link href='http://fonts.googleapis.com/css?family=Pompiere|Amatic+SC:400,700|Delius+Unicase:400,700' rel='stylesheet' type='text/css'>
	

  <%= csrf_meta_tags %>
</head>
<body>
<div class='wrapper'>
	<div class='content'>	
      <nav id='user_nav'>
      <% if current_user then %> 
         <%=link_to "Tancar Sessió de "+current_user.name , logout_path %>
      <% else %>
        <%= link_to "Inicia Sessió", login_path %>
      <% end %>
      </nav>
		<header id="logo">
			<a href="/"><h1>ZOMBIE RECIPES</h1></a>
			<%= image_tag asset_path('eating_brainz.png')%>
		</header>
		<nav id='main'>
			<ul>
				<li><%= link_to "Recipes", recipes_path %></li>
				<li><%= link_to "Zombies", zombies_path %></li>
				<div class='clear'></div>
			</ul>
		</nav>

		<%= yield %>
	</div>
</div>

<footer>
	<div id='transparencia'></div>
	<div class='content'>
		<section>
			<header><h1>Our team</h1></header>
			<article>
				We are David Cortes and Arol Vi&ntilde;olas trying to make something with Ruby on Rails.
				We are both Software Engineer students at FIB (Universitat Politecnica de Catalunya).
				<br/><br/>
				Join the train with us!
			</article>
		</section>
		<div class='separator'></div>
		<section>
			<header><h1>More projects</h1></header>
			<article>
				Our team is working in other web and iOS projects, but they're all top secret! :)
			</article>
		</section>
		<div class='separator'></div>
		<section>
			<header><h1>Find us</h1></header>
			<article>
				You can find us on Twitter (<a href='http://www.twitter.com/davebcn87'>@davebcn87</a> and <a href='http://www.twitter.com/arolet'>@arolet</a> ).
			</article>
		</section>
		<div class='clear'></div>
	</div>
</footer>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p> Estas postejant amb l'usuari <%= current_user.name %></p>
  <%= f.hidden_field :zombie_id, value: current_user.id %>
	
  <div class="field">
    <%= f.label "Titol" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Preparació" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_field :ingredients %>
  </div>
  <div class="field">
    <%= f.label "Temps de cocció" %><br />
    <%= f.time_select :cooktime %>
  </div>
  <div class="field">
    <%= f.label "Imatge" %><br />
    <%= f.text_field :imatge %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Last recipes</h1>

<p><%= link_to content_tag(:span,'New Recipe'), new_recipe_path, class: "new_button" %></p>

<% @recipes.each do |recipe| %>
  <%= div_for (recipe) do %>
    <h2><%= link_to recipe.title, recipe %><h2>
    <h3><%= link_to recipe.zombie.name, recipe.zombie %></h3>
    <%= gravatar_image_tag(recipe.zombie.mail, class: 'gravatar', title: recipe.zombie.name, alt: recipe.zombie.name) %>
    <div class="clear"></div>
    <% if !recipe.imatge.blank? then %>
      <%= image_tag recipe.imatge, class: "imatge" %>
    <% end %>
    <div class="recepta">
      <h4>Elaboration</h4>
      <p class="body"><%= recipe.body %></p>
      <div class='ingredients'>
		<h4>Ingredients</h4>
      	<p><%=  recipe.ingredients %></p>
	  </div>
      <p class="cooktime"><%= recipe.cooktime.to_s(:time) %></p>
      <!-- <%= recipe.rating %> -->
		<div class="rating">

		<% 
			(1..5).each do |i|
				if i <= number_with_precision(recipe.rating, precision: 0).to_i
					classes = ['rating-star', 'achieved']
				else
					classes = ['rating-star']
				end
				%>
				<%= link_to "", vote_recipe_path(recipe), class: classes %>
		<% end %>
		</div>
      <%= content_tag :div, pluralize(recipe.numVotes, "vot"), class: 'numVot' %>
      <!-- <%= link_to 'Show', recipe %> -->
	<div class='clear'></div>
	
      <% if current_user and current_user.id == recipe.zombie_id then %>
        <p>  
           <%= link_to 'Edit', edit_recipe_path(recipe) %>
              <%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %>
        </p>
      <% end %>
    </div>
    <div class="clear"></div>
  </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to content_tag(:span,'New Recipe'), new_recipe_path, class: "new_button" %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<% if current_user %>
  <%= render 'form' %>
<% else %>
  <h2>Has d'<%= link_to "iniciar sessió",login_path  %> per escriure una recepta</h2>
<% end if %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Author:</b>
  <%= link_to @recipe.zombie.name, @recipe.zombie %>
</p>

<p>
  <b>Body:</b>
  <%= @recipe.body %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe.ingredients %>
</p>

<p>
  <b>Cooktime:</b>
  <%= @recipe.cooktime %>
</p>

<p>
  <%= @recipe.rating %> 
	<%= pluralize @recipe.numVotes, "vot" %>
</p>

<p>

</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nom" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Email" %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label "Password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Confirmar assword" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label "Mort" %><br />
    <%= f.date_select :death %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>


<table>
  <tr>
    <th>Name</th>
    <!-- <th>Avatar</th> -->
    <th>Bio</th>
    <th>Death</th>
    <!-- <th></th> -->
    <th></th>
    <th></th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= link_to zombie.name, zombie %></td>
    <!-- <td><%= truncate zombie.avatar %></td> -->
    <td><%= zombie.bio %></td>
    <td><%= zombie.death %></td>
    <!-- <td><%= link_to 'Show', zombie %></td> -->
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/login.html.erb
<h1>Login</h1>
<%= form_tag sessions_path do%>
   <div class="field">
    <%= label_tag "Email" %><br />
    <%= text_field_tag :mail %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <%= submit_tag "Inicia sessió" %>
<% end %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p><%
	if !(@zombie.avatar == "")
		concat image_tag @zombie.avatar, class:'avatar'
	else
		concat "No avatar"
	end
	%>
</p>
	
<p id="notice"><%= notice %></p>

<div class='zombie_info'>
	<p>
	  <b>Name:</b>
	  <%= @zombie.name %>
	</p>

	<p>
	  <b>Bio:</b>
	  <%= @zombie.bio %>
	</p>

	<p>
	  <b>Death:</b>
	  <%= @zombie.death %>
	</p>
</div>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>
<div class='clear'></div>